AWSTemplateFormatVersion : '2010-09-09'
Resources:
  Environment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !ImportValue r6trackercom-Stack-r6trackercom-ApplicationID
      SolutionStackName: 64bit Amazon Linux 2017.09 v2.6.6 running Python 3.6
      OptionSettings:
        -
          Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: c5.xlarge
        -
          Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: "aws-elasticbeanstalk-ec2-role"
      Tier:
        Name: "Worker"
        Type: "SQS/HTTP"
