AWSTemplateFormatVersion: 2010-09-09
Resources:
    r6tracker-backend:
        Type: AWS::ElasticBeanstalk::Application
    environment:
        Type: AWS::ElasticBeanstalk::Environment
        Properties:
            ApplicationName: { Ref: r6tracker-backend }
            SolutionStackName: Python 3.4 version 2.4.1
    appconfig:
        Type: AWS::ElasticBeanstalk::ConfigurationTemplate
        Properties:
            ApplicationName: { Ref: r6tracker-backend }
            EnvironmentId: { Ref: environment }