---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  GitHubUserName:
    Type: String
  GitHubOAuthToken:
    Type: String
    NoEcho: true
Resources:
  ArtifactsBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
  Pipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactsBucket
      Name: 'r6tracker'
      RestartExecutionOnUpdate: true
      RoleArn: !Sub '${PipelineRole.Arn}'
      Stages:
      - Name: Source
        Actions:
        - Name: SourceAction
          ActionTypeId:
            Category: Source
            Owner: ThirdParty
            Provider: GitHub
            Version: 1
          Configuration:
            Owner: !Ref GitHubUserName
            Repo: 'r6tracker'
            Branch: master
            OAuthToken: !Ref GitHubOAuthToken
          OutputArtifacts:
          - Name: Zip
          RunOrder: 1
      - Name: DeployPipeline
        Actions:
        - Name: DeployPipelineAction
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: 1
          Configuration:
            ActionMode: CREATE_UPDATE
            Capabilities: CAPABILITY_IAM
            RoleArn: !Sub '${CloudFormationRole.Arn}'
            StackName: 'r6tracker-DeployStack'
            TemplatePath: 'Zip::pipeline.yml'
            ParameterOverrides: !Sub '{"GitHubUserName": "${GitHubUserName}", "GitHubOAuthToken": "${GitHubOAuthToken}"}'
          InputArtifacts:
          - Name: Zip
          RunOrder: 1
      - Name: DeployApplication
        Actions:
        - Name: DeployApplicationAction
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: ElasticBeanstalk
            Version: 1
          Configuration:
            ApplicationName: !ImportValue r6trackercom-Stack-r6trackercom-ApplicationID
            EnvironmentName: !Ref Environment
          InputArtifacts:
          - Name: Zip
          RunOrder: 1
  PipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'codepipeline.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/AdministratorAccess'
  CloudFormationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'cloudformation.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/AdministratorAccess'
  Environment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !ImportValue r6trackercom-Stack-r6trackercom-ApplicationID
      SolutionStackName: 64bit Amazon Linux 2017.09 v2.6.6 running Python 3.6
      OptionSettings:
        -
          Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: c5.xlarge
        -
          Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: "aws-elasticbeanstalk-ec2-role"
      Tier:
        Name: "Worker"
        Type: "SQS/HTTP"
