AWSTemplateFormatVersion: 2010-09-09
Resources:
    r6trackerBackend:
        Type: AWS::ElasticBeanstalk::Application
    Environment:
        Type: AWS::ElasticBeanstalk::Environment
        Properties:
            ApplicationName: { Ref: r6tracker-backend }
            SolutionStackName: Python 3.4 version 2.4.1
    AppConfig:
        Type: AWS::ElasticBeanstalk::ConfigurationTemplate
        Properties:
            ApplicationName: { Ref: r6tracker-backend }
            EnvironmentId: { Ref: environment }